<?php

namespace Proxies\__CG__\aplicacion\BaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CronTask extends \aplicacion\BaseBundle\Entity\CronTask implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'id', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'descripcion', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'activa', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'asignacionOrdenes', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'comandos', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'intervalo', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'lastrun', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'empresa');
        }

        return array('__isInitialized__', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'id', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'descripcion', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'activa', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'asignacionOrdenes', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'comandos', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'intervalo', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'lastrun', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\CronTask' . "\0" . 'empresa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CronTask $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setComandos($comandos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComandos', array($comandos));

        return parent::setComandos($comandos);
    }

    /**
     * {@inheritDoc}
     */
    public function getComandos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComandos', array());

        return parent::getComandos();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervalo($intervalo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervalo', array($intervalo));

        return parent::setIntervalo($intervalo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervalo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervalo', array());

        return parent::getIntervalo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastrun($lastrun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastrun', array($lastrun));

        return parent::setLastrun($lastrun);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastrun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastrun', array());

        return parent::getLastrun();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiva($activa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiva', array($activa));

        return parent::setActiva($activa);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiva', array());

        return parent::getActiva();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\aplicacion\BaseBundle\Entity\Empresa $empresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignacionOrdenes($asignacionOrdenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignacionOrdenes', array($asignacionOrdenes));

        return parent::setAsignacionOrdenes($asignacionOrdenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignacionOrdenes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignacionOrdenes', array());

        return parent::getAsignacionOrdenes();
    }

}
