<?php

namespace Proxies\__CG__\aplicacion\BaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \aplicacion\BaseBundle\Entity\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'ruc', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'direccion', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'telefono', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'razonsocial', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'email', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'representante', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'ciudad', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'sucursales', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'matriz', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'usuarios', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'ordenes', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'daemons', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'logo', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'feriados', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'agencias', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'configuraciones');
        }

        return array('__isInitialized__', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'ruc', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'direccion', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'telefono', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'razonsocial', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'email', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'representante', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'ciudad', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'sucursales', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'matriz', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'usuarios', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'ordenes', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'daemons', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'logo', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'feriados', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'agencias', '' . "\0" . 'aplicacion\\BaseBundle\\Entity\\Empresa' . "\0" . 'configuraciones');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getConfiguracionActiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguracionActiva', array());

        return parent::getConfiguracionActiva();
    }

    /**
     * {@inheritDoc}
     */
    public function __isMember(\aplicacion\EmisionesBundle\Entity\Agencia $agencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isMember', array($agencia));

        return parent::__isMember($agencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgentes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgentes', array());

        return parent::getAgentes();
    }

    /**
     * {@inheritDoc}
     */
    public function getCounters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCounters', array());

        return parent::getCounters();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabledCounters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabledCounters', array());

        return parent::getEnabledCounters();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnlockedCounters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnlockedCounters', array());

        return parent::getUnlockedCounters();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuc($ruc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuc', array($ruc));

        return parent::setRuc($ruc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuc', array());

        return parent::getRuc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonsocial($razonsocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonsocial', array($razonsocial));

        return parent::setRazonsocial($razonsocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonsocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonsocial', array());

        return parent::getRazonsocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepresentante($representante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepresentante', array($representante));

        return parent::setRepresentante($representante);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentante', array());

        return parent::getRepresentante();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function addSucursale(\aplicacion\BaseBundle\Entity\Empresa $sucursales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSucursale', array($sucursales));

        return parent::addSucursale($sucursales);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSucursale(\aplicacion\BaseBundle\Entity\Empresa $sucursales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSucursale', array($sucursales));

        return parent::removeSucursale($sucursales);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursales', array());

        return parent::getSucursales();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriz(\aplicacion\BaseBundle\Entity\Empresa $matriz = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriz', array($matriz));

        return parent::setMatriz($matriz);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriz', array());

        return parent::getMatriz();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuario(\aplicacion\EmisionesBundle\Entity\Usuariointerno $usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuario', array($usuarios));

        return parent::addUsuario($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuario(\aplicacion\EmisionesBundle\Entity\Usuariointerno $usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuario', array($usuarios));

        return parent::removeUsuario($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', array());

        return parent::getUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($logo));

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function addFeriado(\aplicacion\BaseBundle\Entity\Feriado $feriados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFeriado', array($feriados));

        return parent::addFeriado($feriados);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFeriado(\aplicacion\BaseBundle\Entity\Feriado $feriados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFeriado', array($feriados));

        return parent::removeFeriado($feriados);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeriados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeriados', array());

        return parent::getFeriados();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgencia(\aplicacion\EmisionesBundle\Entity\Agencia $agencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgencia', array($agencias));

        return parent::addAgencia($agencias);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgencia(\aplicacion\EmisionesBundle\Entity\Agencia $agencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgencia', array($agencias));

        return parent::removeAgencia($agencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencias', array());

        return parent::getAgencias();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdene(\aplicacion\EmisionesBundle\Entity\Orden $ordenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdene', array($ordenes));

        return parent::addOrdene($ordenes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdene(\aplicacion\EmisionesBundle\Entity\Orden $ordenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdene', array($ordenes));

        return parent::removeOrdene($ordenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenes', array());

        return parent::getOrdenes();
    }

    /**
     * {@inheritDoc}
     */
    public function addConfiguracione(\aplicacion\BaseBundle\Entity\Configuracion $configuraciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConfiguracione', array($configuraciones));

        return parent::addConfiguracione($configuraciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConfiguracione(\aplicacion\BaseBundle\Entity\Configuracion $configuraciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConfiguracione', array($configuraciones));

        return parent::removeConfiguracione($configuraciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguraciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguraciones', array());

        return parent::getConfiguraciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addDaemon(\aplicacion\BaseBundle\Entity\CronTask $daemons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDaemon', array($daemons));

        return parent::addDaemon($daemons);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDaemon(\aplicacion\BaseBundle\Entity\CronTask $daemons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDaemon', array($daemons));

        return parent::removeDaemon($daemons);
    }

    /**
     * {@inheritDoc}
     */
    public function getDaemons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDaemons', array());

        return parent::getDaemons();
    }

}
