<?php

namespace Proxies\__CG__\aplicacion\EmisionesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agencia extends \aplicacion\EmisionesBundle\Entity\Agencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'id', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'ruc', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'empresas', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'direccion', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'telefono', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'email', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'ciudad', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'logo', 'agentes', 'aerolineasPlanPiloto');
        }

        return array('__isInitialized__', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'id', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'ruc', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'empresas', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'direccion', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'telefono', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'email', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'ciudad', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Agencia' . "\0" . 'logo', 'agentes', 'aerolineasPlanPiloto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuc($ruc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuc', array($ruc));

        return parent::setRuc($ruc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuc', array());

        return parent::getRuc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgente(\aplicacion\EmisionesBundle\Entity\Agente $agentes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgente', array($agentes));

        return parent::addAgente($agentes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgente(\aplicacion\EmisionesBundle\Entity\Agente $agentes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgente', array($agentes));

        return parent::removeAgente($agentes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgentes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgentes', array());

        return parent::getAgentes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(\aplicacion\EmisionesBundle\Entity\Ciudad $ciudad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmpresa(\aplicacion\BaseBundle\Entity\Empresa $empresas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmpresa', array($empresas));

        return parent::addEmpresa($empresas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmpresa(\aplicacion\BaseBundle\Entity\Empresa $empresas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmpresa', array($empresas));

        return parent::removeEmpresa($empresas);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresas', array());

        return parent::getEmpresas();
    }

    /**
     * {@inheritDoc}
     */
    public function addAerolineasPlanPiloto(\aplicacion\EmisionesBundle\Entity\Aerolinea $aerolineasPlanPiloto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAerolineasPlanPiloto', array($aerolineasPlanPiloto));

        return parent::addAerolineasPlanPiloto($aerolineasPlanPiloto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAerolineasPlanPiloto(\aplicacion\EmisionesBundle\Entity\Aerolinea $aerolineasPlanPiloto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAerolineasPlanPiloto', array($aerolineasPlanPiloto));

        return parent::removeAerolineasPlanPiloto($aerolineasPlanPiloto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAerolineasPlanPiloto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAerolineasPlanPiloto', array());

        return parent::getAerolineasPlanPiloto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($logo));

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

}
