<?php

namespace Proxies\__CG__\aplicacion\EmisionesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ciudad extends \aplicacion\EmisionesBundle\Entity\Ciudad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'id', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'descripcion', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'pais', 'ordenes', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'agencias', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'empresas');
        }

        return array('__isInitialized__', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'id', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'descripcion', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'pais', 'ordenes', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'agencias', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Ciudad' . "\0" . 'empresas');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ciudad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais(\aplicacion\EmisionesBundle\Entity\Pais $pais = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', array($pais));

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', array());

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgencia(\aplicacion\EmisionesBundle\Entity\Agencia $agencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgencia', array($agencias));

        return parent::addAgencia($agencias);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgencia(\aplicacion\EmisionesBundle\Entity\Agencia $agencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgencia', array($agencias));

        return parent::removeAgencia($agencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencias', array());

        return parent::getAgencias();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmpresa(\aplicacion\BaseBundle\Entity\Empresa $empresas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmpresa', array($empresas));

        return parent::addEmpresa($empresas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmpresa(\aplicacion\BaseBundle\Entity\Empresa $empresas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmpresa', array($empresas));

        return parent::removeEmpresa($empresas);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresas', array());

        return parent::getEmpresas();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdene(\aplicacion\EmisionesBundle\Entity\Orden $ordenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdene', array($ordenes));

        return parent::addOrdene($ordenes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdene(\aplicacion\EmisionesBundle\Entity\Orden $ordenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdene', array($ordenes));

        return parent::removeOrdene($ordenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenes', array());

        return parent::getOrdenes();
    }

}
