<?php

namespace Proxies\__CG__\aplicacion\EmisionesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tarjetacredito extends \aplicacion\EmisionesBundle\Entity\Tarjetacredito implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'emisorVtc', 'aerolinea', 'bancoEmisorTarjeta', 'tipoTarjeta', 'numeroTarjeta', 'propietario', 'vence', 'pin', 'tipoPago', 'plazo', 'tipoAutorizacion', 'numeroAutorizacion', 'valorTarjeta', 'interesTarjeta', 'valorTotal', 'pagoPasajeros', 'orden');
        }

        return array('__isInitialized__', 'id', 'emisorVtc', 'aerolinea', 'bancoEmisorTarjeta', 'tipoTarjeta', 'numeroTarjeta', 'propietario', 'vence', 'pin', 'tipoPago', 'plazo', 'tipoAutorizacion', 'numeroAutorizacion', 'valorTarjeta', 'interesTarjeta', 'valorTotal', 'pagoPasajeros', 'orden');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tarjetacredito $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmisorVtc($emisorVtc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmisorVtc', array($emisorVtc));

        return parent::setEmisorVtc($emisorVtc);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmisorVtc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmisorVtc', array());

        return parent::getEmisorVtc();
    }

    /**
     * {@inheritDoc}
     */
    public function setAerolinea($aerolinea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAerolinea', array($aerolinea));

        return parent::setAerolinea($aerolinea);
    }

    /**
     * {@inheritDoc}
     */
    public function getAerolinea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAerolinea', array());

        return parent::getAerolinea();
    }

    /**
     * {@inheritDoc}
     */
    public function setBancoEmisorTarjeta($bancoEmisorTarjeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBancoEmisorTarjeta', array($bancoEmisorTarjeta));

        return parent::setBancoEmisorTarjeta($bancoEmisorTarjeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getBancoEmisorTarjeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBancoEmisorTarjeta', array());

        return parent::getBancoEmisorTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoTarjeta($tipoTarjeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoTarjeta', array($tipoTarjeta));

        return parent::setTipoTarjeta($tipoTarjeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoTarjeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoTarjeta', array());

        return parent::getTipoTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTarjeta($numeroTarjeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTarjeta', array($numeroTarjeta));

        return parent::setNumeroTarjeta($numeroTarjeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTarjeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTarjeta', array());

        return parent::getNumeroTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropietario($propietario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropietario', array($propietario));

        return parent::setPropietario($propietario);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropietario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropietario', array());

        return parent::getPropietario();
    }

    /**
     * {@inheritDoc}
     */
    public function setVence($vence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVence', array($vence));

        return parent::setVence($vence);
    }

    /**
     * {@inheritDoc}
     */
    public function getVence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVence', array());

        return parent::getVence();
    }

    /**
     * {@inheritDoc}
     */
    public function setPin($pin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPin', array($pin));

        return parent::setPin($pin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPin', array());

        return parent::getPin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoPago($tipoPago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoPago', array($tipoPago));

        return parent::setTipoPago($tipoPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoPago', array());

        return parent::getTipoPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlazo($plazo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlazo', array($plazo));

        return parent::setPlazo($plazo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlazo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlazo', array());

        return parent::getPlazo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoAutorizacion($tipoAutorizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoAutorizacion', array($tipoAutorizacion));

        return parent::setTipoAutorizacion($tipoAutorizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoAutorizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoAutorizacion', array());

        return parent::getTipoAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroAutorizacion($numeroAutorizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroAutorizacion', array($numeroAutorizacion));

        return parent::setNumeroAutorizacion($numeroAutorizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroAutorizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroAutorizacion', array());

        return parent::getNumeroAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTarjeta($valorTarjeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTarjeta', array($valorTarjeta));

        return parent::setValorTarjeta($valorTarjeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTarjeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTarjeta', array());

        return parent::getValorTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setInteresTarjeta($interesTarjeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInteresTarjeta', array($interesTarjeta));

        return parent::setInteresTarjeta($interesTarjeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getInteresTarjeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInteresTarjeta', array());

        return parent::getInteresTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTotal($valorTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTotal', array($valorTotal));

        return parent::setValorTotal($valorTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTotal', array());

        return parent::getValorTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoPasajeros($pagoPasajeros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoPasajeros', array($pagoPasajeros));

        return parent::setPagoPasajeros($pagoPasajeros);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoPasajeros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoPasajeros', array());

        return parent::getPagoPasajeros();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden(\aplicacion\EmisionesBundle\Entity\Orden $orden = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', array($orden));

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', array());

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdene(\aplicacion\EmisionesBundle\Entity\Orden $ordenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdene', array($ordenes));

        return parent::addOrdene($ordenes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdene(\aplicacion\EmisionesBundle\Entity\Orden $ordenes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdene', array($ordenes));

        return parent::removeOrdene($ordenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenes', array());

        return parent::getOrdenes();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

}
