<?php

namespace Proxies\__CG__\aplicacion\EmisionesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aerolinea extends \aplicacion\EmisionesBundle\Entity\Aerolinea implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'id', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'iata', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'descripcion', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'fpTarjetasCredito', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'agenciasPlanPiloto');
        }

        return array('__isInitialized__', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'id', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'nombre', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'iata', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'descripcion', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'fpTarjetasCredito', '' . "\0" . 'aplicacion\\EmisionesBundle\\Entity\\Aerolinea' . "\0" . 'agenciasPlanPiloto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Aerolinea $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function addFpTarjetasCredito(\aplicacion\EmisionesBundle\Entity\Tarjetacredito $fpTarjetasCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFpTarjetasCredito', array($fpTarjetasCredito));

        return parent::addFpTarjetasCredito($fpTarjetasCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFpTarjetasCredito(\aplicacion\EmisionesBundle\Entity\Tarjetacredito $fpTarjetasCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFpTarjetasCredito', array($fpTarjetasCredito));

        return parent::removeFpTarjetasCredito($fpTarjetasCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getFpTarjetasCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFpTarjetasCredito', array());

        return parent::getFpTarjetasCredito();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgenciasPlanPiloto(\aplicacion\EmisionesBundle\Entity\Agencia $agenciasPlanPiloto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgenciasPlanPiloto', array($agenciasPlanPiloto));

        return parent::addAgenciasPlanPiloto($agenciasPlanPiloto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgenciasPlanPiloto(\aplicacion\EmisionesBundle\Entity\Agencia $agenciasPlanPiloto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgenciasPlanPiloto', array($agenciasPlanPiloto));

        return parent::removeAgenciasPlanPiloto($agenciasPlanPiloto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenciasPlanPiloto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenciasPlanPiloto', array());

        return parent::getAgenciasPlanPiloto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIata($iata)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIata', array($iata));

        return parent::setIata($iata);
    }

    /**
     * {@inheritDoc}
     */
    public function getIata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIata', array());

        return parent::getIata();
    }

}
